# Generated by Django 4.2.7 on 2023-12-02 02:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Studious", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="major",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="school",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="year",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
