# Generated by Django 4.2.7 on 2023-12-02 03:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Studious", "0002_alter_userprofile_major_alter_userprofile_school_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="studysession",
            name="location",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="studysession",
            name="session_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="studysession",
            name="time_posted",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
